from __future__ import annotations

import asyncio
import json
import time
from typing import Any

from fastapi import FastAPI, HTTPException
from loguru import logger

from ollama_client import OLLAMA_MODEL, check_ollama_health, generate
from prompts import SYSTEM_PROMPT, build_viability_prompt
from report_schema import ReportRequest, ReportResponse, ViabilityReport

app = FastAPI(title="GeoSmart Advisor Intelligence", version="1.0.0")


def _strip_markdown_fences(text: str) -> str:
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned[3:]
        if cleaned.lstrip().startswith("json"):
            cleaned = cleaned.lstrip()[4:]
        cleaned = cleaned.strip()
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]
    return cleaned.strip()


def _parse_report(raw_text: str) -> ViabilityReport:
    cleaned = _strip_markdown_fences(raw_text)
    payload = json.loads(cleaned)
    return ViabilityReport.model_validate(payload)


def _fallback_report(request: ReportRequest) -> tuple[ViabilityReport, str]:
    score = float(request.score)
    if score >= 85:
        rating = "Excellent"
    elif score >= 70:
        rating = "Good"
    elif score >= 55:
        rating = "Moderate"
    elif score >= 40:
        rating = "Poor"
    else:
        rating = "Avoid"

    strength_1 = f"Quantitative viability is {score:.1f}/100, which supports a {rating.lower()} commercial outlook."
    strength_2 = f"Local feature profile suggests a measurable match between location conditions and the proposed concept in {request.location_name}."
    strength_3 = "Structured inputs provide a reproducible baseline for further site comparison."
    risk_1 = "The report is template-generated because Ollama was unavailable or unprepared."
    risk_2 = "A fallback report cannot reason beyond the supplied structured features."

    report = ViabilityReport(
        headline=f"{request.location_name} shows a {rating.lower()} operating profile at {score:.1f}/100.",
        viability_rating=rating,  # type: ignore[arg-type]
        top_strengths=[strength_1, strength_2, strength_3],
        top_risks=[risk_1, risk_2],
        competitor_analysis=(
            f"Competition is inferred from the structured inputs and score rather than a narrative model. "
            f"Use the competitor count and market gap signals to confirm the local landscape before execution."
        ),
        demographic_fit=(
            f"The demographic fit is anchored to the supplied density and income proxies. "
            f"For {request.location_name}, the current quantitative score implies the market may or may not support premium positioning depending on segment." 
        ),
        recommendation=(
            f"Generated by fallback_template: validate {request.location_name} with one field visit, two competitor checks, and a quick unit economics test before committing capital."
        ),
        confidence=max(0.25, min(0.7, score / 100.0)),
    )
    raw_text = json.dumps(
        {
            "generated_by": "fallback_template",
            "headline": report.headline,
            "viability_rating": report.viability_rating,
            "top_strengths": report.top_strengths,
            "top_risks": report.top_risks,
            "competitor_analysis": report.competitor_analysis,
            "demographic_fit": report.demographic_fit,
            "recommendation": report.recommendation,
            "confidence": report.confidence,
        },
        ensure_ascii=False,
    )
    return report, raw_text


async def _generate_once(request: ReportRequest, strict: bool = False) -> str:
    prompt = build_viability_prompt(request.features, request.score, request.location_name)
    if strict:
        prompt = prompt + "\nReturn ONLY valid JSON. No markdown. No explanation. Just the JSON object."
    return await generate(prompt=prompt, system=SYSTEM_PROMPT)


async def _render_report(request: ReportRequest) -> tuple[ViabilityReport, str, bool]:
    try:
        raw_text = await _generate_once(request)
        report = _parse_report(raw_text)
        return report, raw_text, True
    except Exception as first_error:
        logger.warning("Primary generation failed, retrying with stricter prompt: {}", first_error)
        try:
            raw_text = await _generate_once(request, strict=True)
            report = _parse_report(raw_text)
            return report, raw_text, True
        except Exception as second_error:
            logger.warning("Ollama generation unavailable, using fallback template: {}", second_error)
            report, raw_text = _fallback_report(request)
            return report, raw_text, False


@app.on_event("startup")
async def startup_event() -> None:
    try:
        available = await check_ollama_health()
        app.state.ollama_available = available
    except Exception as error:
        app.state.ollama_available = False
        logger.warning("Ollama health check failed; fallback reports will be used: {}", error)


@app.get("/health")
async def health() -> dict[str, Any]:
    return {
        "status": "ok",
        "model": OLLAMA_MODEL,
        "ollama_available": bool(getattr(app.state, "ollama_available", False)),
    }


@app.post("/report", response_model=ReportResponse)
async def report(request: ReportRequest) -> ReportResponse:
    started = time.perf_counter()
    try:
        report_model, raw_text, _ = await _render_report(request)
    except Exception as error:
        raise HTTPException(status_code=500, detail=str(error)) from error

    elapsed_ms = (time.perf_counter() - started) * 1000.0
    return ReportResponse(report=report_model, raw_text=raw_text, generation_time_ms=elapsed_ms)


@app.post("/batch_report", response_model=list[ReportResponse])
async def batch_report(requests: list[ReportRequest]) -> list[ReportResponse]:
    semaphore = asyncio.Semaphore(3)

    async def _bounded_report(item: ReportRequest) -> ReportResponse:
        async with semaphore:
            return await report(item)

    return await asyncio.gather(*[_bounded_report(item) for item in requests])


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("server:app", host="0.0.0.0", port=8003, reload=False)
